<? $this->view->partial('shared/city_header', Array('title' => 'Реферальная программа')); ?>
<div class="textblock">
	<table cellspacing='0' cellpadding='0' class='ltable'>
		<tr>
			<td valign="top">
				<font color="red">Ваша реферальная ссылка (для регистраций) - </font>
				<font color="blue">
					<b><a href="http://<?=$_SERVER['SERVER_NAME'] ?>/?<?=$this->user->id ?>" target="_blank">http://<?=$_SERVER['SERVER_NAME'] ?>/?<?=$this->user->id ?></a></b>
				</font>
				<br>
				<? if (count($refers)): ?>
					<font color=navy><b>Привлеченные вами игроки:</b></font>
					<table class="table">
						<thead>
							<tr>
								<th>Имя</th>
								<th>Уровень</td>
								<th>Статус</th>
							</tr>
						</thead>
						<tbody>
							<? foreach ($refers as $user): ?>
								<tr>
									<td class="text-center"><?=$user['username'] ?></td>
									<td class="text-center"><?=$user['level'] ?></td>
									<td class="text-center">
										<? if (time() - $user['lpv'] < 180): ?>
											<font color="green">OnLine</font>
										<? else: ?>
											<font color="red">OffLine</font>
										<? endif; ?>
									</td>
								</tr>
							<? endforeach; ?>
						</tbody>
					</table>
				<? endif; ?>
			</td>
		</tr>
	</table>
</div>