<?php

namespace App\Engine\Battle\Abilities;

class AbilityRegistry
{
	/** @var array<int, Ability>|null */
	private static ?array $abilities = null;

	public static function find(?int $id): ?Ability
	{
		if ($id === null) {
			return null;
		}

		return self::all()[$id] ?? null;
	}

	/** @return array<int, Ability> */
	public static function all(): array
	{
		return self::$abilities ??= [
			1 => new Ability(
				id: 1,
				name: 'Аура исцеления',
				description: 'В течении 3 ходов вы востанавливаете по 5 HP за ход',
				level: 0,
				wait: 1,
				duration: 3,
				effect: new AbilityEffect(healing: 5),
				critCost: 3,
				hpCost: 5,
			),
			5 => new Ability(
				id: 5,
				name: 'Испепеление',
				description: 'Наносит цели дополнительно 50 урона огнём',
				level: 0,
				wait: 1,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 50),
				spiritCost: 5,
				hpCost: 5,
			),
			6 => new Ability(
				id: 6,
				name: 'Ярость',
				description: 'На 3 хода ваш урон увеличен на 5',
				level: 0,
				wait: 1,
				duration: 3,
				effect: new AbilityEffect(damageBonus: 5),
				critCost: 4,
				hpCost: 4,
			),
			7 => new Ability(
				id: 7,
				name: 'Усиленный удар',
				description: 'Следующий ваш удар нанесёт на 3 урона больше',
				level: 1,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 3),
				hpCost: 1,
			),
			8 => new Ability(
				id: 8,
				name: 'Блок',
				description: 'Следующий удар по вам нанесет на 3 урона меньше',
				level: 1,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageReduction: 3),
				hpCost: 1,
			),
			9 => new Ability(
				id: 9,
				name: 'Вытереть кровоподтек',
				description: 'Восстановить 3 HP',
				level: 1,
				wait: 1,
				duration: 1,
				effect: new AbilityEffect(healing: 3),
				hpCost: 1,
			),
			10 => new Ability(
				id: 10,
				name: 'Усиленный удар II',
				description: 'Следующий ваш удар нанесёт на 5 урона больше',
				level: 2,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 5),
				hpCost: 2,
			),
			11 => new Ability(
				id: 11,
				name: 'Блок II',
				description: 'Следующий удар по вам нанесет на 5 урона меньше',
				level: 2,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageReduction: 5),
				hpCost: 2,
			),
			12 => new Ability(
				id: 12,
				name: 'Вытереть кровоподтек II',
				description: 'Восстановить 5 HP',
				level: 2,
				wait: 1,
				duration: 1,
				effect: new AbilityEffect(healing: 5),
				hpCost: 2,
			),
			13 => new Ability(
				id: 13,
				name: 'Точный удар',
				description: 'Следующий ваш удар наносит на 10 урона больше',
				level: 3,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 10),
				hpCost: 3,
			),
			14 => new Ability(
				id: 14,
				name: 'Сильный Удар',
				description: 'Следующий ваш удар наносит на 20 урона больше',
				level: 3,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 15),
				hpCost: 4,
			),
			15 => new Ability(
				id: 15,
				name: 'Вытереть Пот',
				description: 'Восстанавливает 10 HP',
				level: 3,
				wait: 1,
				duration: 1,
				effect: new AbilityEffect(healing: 10),
				hpCost: 3,
			),
			16 => new Ability(
				id: 16,
				name: 'Точный удар II',
				description: 'Следующий ваш удар нанесёт на 15 урона больше',
				level: 4,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 15),
				hpCost: 4,
			),
			17 => new Ability(
				id: 17,
				name: 'Сильный Удар II',
				description: 'Следующий ваш удар нанесёт на 25 урона больше',
				level: 4,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 25),
				hpCost: 5,
			),
			18 => new Ability(
				id: 18,
				name: 'Вытереть Пот II',
				description: 'Восстанавливает 20 HP',
				level: 4,
				wait: 1,
				duration: 1,
				effect: new AbilityEffect(healing: 20),
				parryCost: 1,
				hpCost: 3,
			),
			19 => new Ability(
				id: 19,
				name: 'Удачный Блок',
				description: 'Урон по вам уменьшен на 10',
				level: 4,
				wait: 1,
				duration: 1,
				effect: new AbilityEffect(damageReduction: 10),
				blockCost: 3,
				hpCost: 1,
			),
			4 => new Ability(
				id: 4,
				name: 'Промах',
				description: 'Вы увернетесь от следующего удара по вам',
				level: 4,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(forceDodge: true),
				blockCost: 1,
				parryCost: 3,
				hpCost: 1,
			),
			3 => new Ability(
				id: 3,
				name: 'Удар по больному месту',
				description: 'Следующий ваш удар будет критическим',
				level: 4,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(forceCrit: true),
				critCost: 2,
				hpCost: 3,
			),
			20 => new Ability(
				id: 20,
				name: 'Точный удар III',
				description: 'Следующий ваш удар нанесёт на 20 урона больше',
				level: 5,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 20),
				hpCost: 6,
			),
			21 => new Ability(
				id: 21,
				name: 'Сильныйй Удар III',
				description: 'Следующий ваш удар нанесёт на 30 урона больше',
				level: 5,
				wait: 2,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 30),
				hpCost: 7,
			),
			22 => new Ability(
				id: 22,
				name: 'Вытереть Пот III',
				description: 'Восстанавливает 30 HP',
				level: 5,
				wait: 1,
				duration: 1,
				effect: new AbilityEffect(healing: 30),
				parryCost: 1,
				hpCost: 3,
			),
			2 => new Ability(
				id: 2,
				name: 'Подлый удар',
				description: 'Текущий удар увеличивается на 35 ед.',
				level: 5,
				wait: 1,
				duration: 1,
				effect: new AbilityEffect(damageBonus: 35),
				hpCost: 11,
			),
		];
	}
}
