<?= $this->tag->getDoctype() ?>
<html>
	<head>
		<?php echo $this->tag->getTitle(); ?>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="shortcut icon" href="/favicon.ico">
		<?php $this->assets->outputCss('cssHeader') ?>
		<?php $this->assets->outputJs('jsHeader') ?>
		<script type="text/javascript">
			var timestamp = <?=time() ?>;
			var timezone = 0;
			var addToUrl = '';
			var isAjax = false;
		</script>
	</head>
	<body>
		<?php echo $this->getContent() ?>
	</body>
</html>